import Head from 'next/head'
import Navbar from '../components/Navbar'
import { useState } from 'react'
import Sidebar from '../components/Sidebar';
<<<<<<< HEAD
import Main from '../components/ProfitGraphs/Main';
=======
import Footer from '../components/Footer';
>>>>>>> 3ea2e1745a792cab84a16ba760fcadf46c91a4f6


export default function ProfitTabela() {
  const [isOpen, setIsOpen] = useState(false);
  const toggle = () => {
    setIsOpen(!isOpen);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Sidebar toggle={toggle} isOpen={isOpen}/>
<<<<<<< HEAD
        <Main toggle={toggle} isOpen={isOpen}/>
=======
        <Footer />
>>>>>>> 3ea2e1745a792cab84a16ba760fcadf46c91a4f6
      </div>
      
  )
}